language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - ree
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
script: bundle exec rake test
